server:
  port: 9001

spring:
  application:
    name: config
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pattadonpro/central-config.git
          cloneOnStart: true
          defaultLabel: main
