server:
  port: 8888

spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: /Users/pattadon.pro/Desktop/max/merchant-project/central-config
